#!/bin/bash

if [ "$USER" == "will" ]; then
    UN=wdeberry
elif
    [ "$USER" == "rob" ]; then
    UN=rob
else
    echo "Please type your Username: "
    read UN
fi

sshpass -f ~/.apssh ssh -oStrictHostKeyChecking=no $2 $3 ${UN}@appserver.$1.gwn
