#!/bin/bash

CLOUD=/home/$USER/android/updates
BUILD_DIR=/home/$USER/android/builds/aokp
OUT=out/target/product/tf101
CCACHE=$BUILD_DIR/prebuilt/linux-x86/ccache
Option1="Repo Sync"
Option2="Build for TF101"
Option3="Build for Toro"
Option4="Clean then Build TF101"
Option5="Clean then Build Toro"

export USE_CCACHE=1
export CCACHE_DIR=/home/$USER/android/.ccache

function sync {
    cd $BUILD_DIR
    repo sync -j16
}

function tf101 {
    cd $CCACHE
    ./ccache -M 40G
    cd $BUILD_DIR
    . build/envsetup.sh
    brunch tf101
    scp out/target/product/tf101/aokp_tf101_*.zip storage:/home/will/Dropbox/Public/android/updates/
}

function toro {
    cd $CCACHE
    ./ccache -M 40G
    cd $BUILD_DIR
    . build/envsetup.sh
    brunch toro
    scp out/target/product/toro/aokp_toro_*.zip storage:/home/will/Dropbox/Public/android/updates/
}

function clean {
    cd $BUILD_DIR
    . build/envsetup.sh
    lunch aokp_tf101-userdebug
    make clean -j16
}

PS3='Please enter your choice: '
options=("$Option1" "$Option2" "$Option3" "$Option4" "$Option5" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "$Option1")
            sync
            break
            ;;
        "$Option2")
            tf101
            break
            ;;
        "$Option3")
            toro
            break
            ;;
        "$Option4")
            clean
            tf101
            break
            ;;
        "$Option5")
            clean
            toro
            break
            ;;
        "Quit")
            break
            ;;
        *) echo invalid option;;
    esac
done
