#!/bin/bash

BUILD_DIR=/home/$USER/jb-aokp

export USE_CCACHE=1
export CCACHE_DIR=/home/$USER/.ccache

ACTION=$1
DEVICE=$2

function sync {
    cd $BUILD_DIR
    repo sync -j32
}

function build {
    ccache -M 40G
    cd $BUILD_DIR
    . build/envsetup.sh
    brunch $ACTION
    find . -name aokp_${ACTION}_\*.zip -exec scp {} home:/home/will/updates/ \; -exec echo 
                 "Successfully copied to Dropbox..." \;
}

function clean {
    cd $BUILD_DIR
    . build/envsetup.sh
    lunch aokp_$DEVICE-userdebug
    make clean -j16
}

function clobber {
    cd $BUILD_DIR
    . build/envsetup.sh
    make clobber -j16
}

if [ "$ACTION" = "sync" ];
then
    sync
elif [ "$ACTION" = "clean" ];
then
    clean
elif [ "$ACTION" = "clobber" ];
then
    clobber
else
    build
fi
