#!/bin/bash

CLOUD=/home/konrad/android/updates
BUILD_DIR=/home/konrad/android/builds/cm9
OUT=out/target/product/PHONE
PHONE=

export USE_CCACHE=1
export CCACHE_DIR=/home/konrad/android/.ccache
prebuilt/linux-x86/ccache/ccache -M 40G

printf "Compile for which HTC Phone?"
read PHONE

cd $BUILD_DIR
repo sync -j16
make clean -j16
. build/envsetup.sh && lunch htc_$PHONE-eng && make -j2 otapackage
mv $OUT/htc_*.zip $CLOUD/$PHONE-cm9.zip
