#!/bin/bash

CLOUD=/home/$USER/android/updates
BUILD_DIR=/home/$USER/android/builds/cm9
OUT=out/target/product/toro
CCACHE=$BUILD_DIR/prebuilt/linux-x86/ccache
Option1="Repo Sync"
Option2="Build for Toro"
Option3="Build for TF101"
Option4="Clean Build"

export USE_CCACHE=1
export CCACHE_DIR=/home/$USER/android/.ccache

function sync {
    cd $BUILD_DIR
    repo sync -j16
}

function toro {
    cd $CCACHE
    ./ccache -M 40G
    sync
    . build/envsetup.sh
    lunch cm_toro-userdebug
    ./vendor/cm/get-prebuilts
    make -j4 otapackage
    ssh storage -t cp /home/downloads/android/builds/cm9/out/target/product/toro/cm_toro-ota-eng.will.zip /home/will/Dropbox/Public/android/updates/toro-cm9.zip
}

function tf101 {
    cd $CCACHE
    ./ccache -M 40G
    sync
    . build/envsetup.sh
    lunch cm_tf101-userdebug
    ./vendor/cm/get-prebuilts
    make -j4 otapackage
    ssh storage -t cp /home/downloads/android/builds/cm9/out/target/product/tf101/cm_tf101-ota-eng.will.zip /home/will/Dropbox/Public/android/updates/tf101-cm9.zip
}

function clean {
    cd $BUILD_DIR
    make clean -j16
}

PS3='Please enter your choice: '
options=("$Option1" "$Option2" "$Option3" "$Option4" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "$Option1")
            sync
            break
            ;;
        "$Option2")
            toro
            break
            ;;
        "$Option3")
            tf101
            break
            ;;
        "$Option4")
            clean
            break
            ;;
        "Quit")
            break
            ;;
        *) echo invalid option;;
    esac
done
