#!/bin/bash

if [ "$USER" == "will" ]; then
    UN=wdeberry
elif
    [ "$USER" == "rob" ]; then
    UN=rglass
else
    echo "Please type your Username: "
    read UN
fi

sshpass -f ~/.apssh ssh -oStrictHostKeyChecking=no $2 ${UN}@db.$1.gwn
