#!/bin/bash
IP=${@: -1}
SSH_OPTS="-o StrictHostKeyChecking=no -l root"
SSHP_OPTS="-f ~/.plcssh"

function audio {
    sshpass $SSHP_OPTS ssh $SSH_OPTS $IP -T <<'EOFSSH'

    cat /opt/GWN/conf/audio.conf

EOFSSH
}

function config {
    sshpass $SSHP_OPTS ssh $SSH_OPTS $IP -T <<'EOFSSH'

    if [ -e "/opt/GWN/conf/DisplayConfig.xml" ]; then
        cat /opt/GWN/conf/DisplayConfig.xml
  else
        echo "PLC uses properties and not the displays XML"
    fi

EOFSSH
}

function display {
    sshpass $SSHP_OPTS ssh $SSH_OPTS $IP -T <<'EOFSSH'

    if [ -e "/opt/GWN/scripts/display/DisplayControl.sh" ]; then
        /opt/GWN/scripts/display/DisplayControl.sh Info
    else
        queryProperties --display-control
    fi

EOFSSH
}

function edid {
    sshpass $SSHP_OPTS ssh $SSH_OPTS $IP -T <<'EOFSSH'

    getedidinfo identity

EOFSSH
}

function fetch {
    sshpass $SSHP_OPTS ssh $SSH_OPTS $IP -T <<'EOFSSH'

    doFetch --all && RDC reconfigure_display && /etc/init.d/patientx restart

EOFSSH
}


function getLogs {
    if [ ! -d ~/logs ]; then
      mkdir ~/logs
    fi

    echo "Getting log from $IP"
    sshpass $SSHP_OPTS scp -oStrictHostKeyChecking=no root@$IP:/var/log/messages ~/logs/${IP}_messages.log
}

function help {
    echo -e "\nusage: info [OPTIONS] IPADDRESS \n"

    echo -e "Options:
  -a, --audio     Prints out the current audio config
  -c, --config    Displays the current display config used by the PLC
  -d, --display   Prints out the current display config
  -e, --edid      Displays the EDID of the currently connected TV
  -f, --fetch     Forces the PLC to manually fetch the newest displays
                  XML and apply it via patient experience restart
  -g, --getlogs   downloads the current /var/log/messages file to ~/logs/
  -h, --help      Show this help message and exit
  -i, --ipaddress Displays all the PLCs network information
  -m, --motd      Prints out the PLCs helpme prompt
  -r, --reboot    Reboots the PLC
  -x, --restart   Restarts the patient experience
  -z, --rez       Displays the current resolution of the PLC"

}

function ipaddress {
    sshpass $SSHP_OPTS ssh $SSH_OPTS $IP -T <<'EOFSSH'

    YELLOW="$( echo -e "\e[33;01m" )"
    PURPLE="$( echo -e "\e[35;01m" )"
    PLAIN="$( echo -e "\e[0m" )"

    DNS=$(cat /etc/resolv.conf | awk '{print $2}')
    IP=$(cat /etc/conf.d/net | grep -i config | cut -f2 -d '"' | awk '{print $1}')
    MASK=$(cat /etc/conf.d/net | grep -i config | cut -f2 -d '"' | awk '{print $3}')
    GATEWAY=$(cat /etc/conf.d/net | grep -i routes | cut -f2 -d '"' | awk '{print $3}')

    cat <<NETWORK
${YELLOW}Network Information:${PLAIN}
    ${PURPLE}IPAddress: ${YELLOW}$IP
    ${PURPLE}Subnet: ${YELLOW}$MASK
    ${PURPLE}DNS: ${YELLOW}$DNS
    ${PURPLE}Gateway: ${YELLOW}$GATEWAY${PLAIN}
NETWORK

EOFSSH
}

function motd {
    sshpass $SSHP_OPTS ssh $SSH_OPTS $IP -T <<'EOFSSH'

    helpme --motd

EOFSSH
}

function patientx {
    sshpass $SSHP_OPTS ssh $SSH_OPTS $IP -T <<'EOFSSH'

    RDC sanitize

EOFSSH
}


function reboot {
    sshpass $SSHP_OPTS ssh $SSH_OPTS $IP -T <<'EOFSSH'

    RDC reboot

EOFSSH
}

function resolution {
    sshpass $SSHP_OPTS ssh $SSH_OPTS $IP -T <<'EOFSSH'

    xvidtune -show

EOFSSH
}


for arg
do
    delim=""
    case "$arg" in
        --audio) args="${args} -a ";;
        --config) args="${args} -c ";;
        --display) args="${args} -d ";;
        --edid) args="${args} -e ";;
        --fetch) args="${args} -f ";;
        --getlogs) args="${args} -g ";;
        --help) args="${args} -h ";;
        --ipaddress) args="${args} -i ";;
        --motd) args="${args} -m ";;
        --reboot) args="${args} -r ";;
        --restart) args="${args} -x ";;
        --rez) args="${args} -z ";;
        *) [[ "${arg:0:1}" == "-" ]] || delim="\""
        args="${args}${delim}${arg}${delim} ";;
    esac
done

eval set -- $args
    while getopts ":acdefghimrxz?" option 2>/dev/null
    do
        case $option in
            a) audio
                ;;
            c) config
                ;;
            d) display
                ;;
            e) edid
                ;;
            f) fetch
                ;;
            g) getLogs
                ;;
            h) help
                exit
                ;;
            i) ipaddress
                ;;
            m) motd
                ;;
            r) reboot
                ;;
            x) patientx
                ;;
            z) resolution
                ;;
            *) echo $OPTARG is an unrecognized option;
                help
                exit
                ;;
        esac
    done
