#!/bin/bash

MOUNT=$(mount | grep -i storage)
DIR="/home/${USER}/storage"
REMOTE="nas:/mnt/Storage/Public"

if [ -z "$MOUNT" ]; then
    if [ ! -d "$DIR" ]; then
        mkdir $DIR
    fi
        sudo mount -t nfs -o nolock $REMOTE $DIR
else
    sudo umount $DIR
fi
