#!/bin/bash

MOUNT=$(mount | grep -i storage)
DIR="/mnt/storage"
REMOTE="nas:/mnt/Storage/Public"

if [ -z "$MOUNT" ]; then
    if [ -d "$DIR" ]; then
        sudo mount -t nfs -o nolock $REMOTE $DIR
    else
        mkdir $DIR
        sudo mount -t nfs -o nolock $REMOTE $DIR
    fi
else
    sudo umount $DIR
fi
