#!/bin/bash

DEVICE=${1}

scp rainbow.aokp.co:/home/will/kk/out/target/product/${DEVICE}/system/priv-app/ROMControl.apk ~/Downloads/.
adb start-server
adb remount
adb push ~/Downloads/ROMControl.apk /system/priv-app/ROMControl.apk
sleep 2
adb shell am start -n com.aokp.romcontrol/com.aokp.romcontrol.MainActivity
