#!/bin/bash
SCRIPTS=/home/$USER/.config/conky

if [ -n "$(ps ax | grep -i '[c]onky' | grep -v rconky)" ]; then
    pkill conky
else
    sleep 5
    conky -c $SCRIPTS/rings &
    sleep 5
    conky -c $SCRIPTS/cpu &
    conky -c $SCRIPTS/procs &
    conky -c $SCRIPTS/ram &
    conky -c $SCRIPTS/mem
fi
