#!/bin/bash

CLOUD=/home/konrad/android/updates
VISION=/home/konrad/android/builds/cm7
OUT=out/target/product/PHONE
PHONE=

export USE_CCACHE=1
export CCACHE_DIR=/home/konrad/android/.ccache
prebuilt/linux-x86/ccache/ccache -M 40G

printf "Compile for which Phone?"
read PHONE

cd $VISION
repo sync -j16
make clean -j16
cd vendor/cyanogen/
./get-rommanager
cd $VISION
. build/envsetup.sh && brunch $PHONE
mv $OUT/update-cm*.zip $CLOUD/$PHONE-cm7.zip
