#!/bin/bash

function controlWinXP {
    VM=$(ps ax | grep -i "[W]indows XP")
    if [ -n "$VM" ]; then
        vboxmanage controlvm "Windows XP" poweroff
    else
        vboxmanage startvm "Windows XP"
    fi
}

function controlMalXP {
    VM=$(ps ax | grep -i "[M]alXP")
    if [ -n "$VM" ]; then
        vboxmanage controlvm "MalXP" poweroff
    else
        vboxmanage startvm "MalXP"
    fi
}

function controlWin7 {
    VM=$(ps ax | grep -i "[W]in7")
    if [ -n "$VM" ]; then
        vboxmanage controlvm "Win7" poweroff
    else
        vboxmanage startvm "Win7"
    fi
}

if [ -z "$1" ]; then
    controlWinXP
else
    case $1 in   
        M)
            controlMalXP
            exit
            ;;
        7)
            controlWin7
            exit
            ;;
    esac
fi
